import os
import git
import json
from datetime import datetime, timezone
from typing import Dict, Any, List, Optional
from pathlib import Path

from .handover_manager import HandoverManager, HandoverState


class HandoverDocumentGenerator:
    """Automated generation of comprehensive handover documents"""
    
    def __init__(self, handover_manager: HandoverManager):
        self.handover_manager = handover_manager
        self.template_path = Path(__file__).parent / "templates" / "handover_template.md"
        
    def generate_full_handover_document(self, 
                                      coder=None, 
                                      reason="session_completion",
                                      trigger="automated") -> str:
        """Generate complete LLM_HANDOVER.md with current session state"""
        
        # Capture current state
        state = self.handover_manager.capture_current_state(coder, reason, trigger)
        
        # Generate git information
        git_info = self._get_detailed_git_info()
        
        # Generate work summary
        work_summary = self._generate_work_summary(state)
        
        # Generate pending tasks
        pending_tasks = self._generate_pending_tasks(state)
        
        # Generate next LLM instructions
        next_instructions = self._generate_next_instructions(state)
        
        # Build document
        document = f"""# LLM Session Handover

This document summarizes the progress and context of the current development session, intended for seamless handover to another LLM.

**Generated:** {state.timestamp}
**Session ID:** {state.session_id}
**Handover Reason:** {state.handover_reason}

## Project Context

**Current Project Root:** `{state.working_directory}`
**Current Git Branch:** `{state.git_branch}`
**Current Git Commit:** `{state.git_commit}`
**Atlas Version:** `{state.atlas_version}`

{git_info}

## Model Configuration

**Main Model:** {state.main_model.get('name', 'unknown')}
**Editor Model:** {state.editor_model.get('name', 'none') if state.editor_model else 'none'}
**Weak Model:** {state.weak_model.get('name', 'none') if state.weak_model else 'none'}
**Current Coder Type:** {state.current_coder_type}
**Edit Format:** {state.edit_format}

## Session Metrics

**Session Duration:** {state.session_duration:.1f} seconds
**Token Usage:** {self._format_token_usage(state.token_usage)}
**Success Metrics:** {self._format_success_metrics(state.success_metrics)}

## File Context

### Active Files ({len(state.active_files)})
{self._format_file_list(state.active_files)}

### Read-Only Files ({len(state.read_only_files)})
{self._format_file_list(state.read_only_files)}

## Work Completed in this Session

{work_summary}

## Conversation Summary

{state.chat_history_summary if state.chat_history_summary else "No conversation history available."}

## Pending Tasks / Next Steps

{pending_tasks}

## Instructions for the Next LLM

{next_instructions}

## Session State Validation

**Validation Checksum:** `{state.validation_checksum}`
**State File:** `.aider.handover.state.json`

To restore this session state, use:
```python
from aider.handover_manager import HandoverManager
manager = HandoverManager()
state = manager.load_handover_state()
```

## Configuration Context

### Environment Variables (Safe)
{self._format_env_vars(state.environment_variables)}

### User Preferences
{self._format_user_preferences(state.user_preferences)}

---
*This handover document was automatically generated by the Atlas Handover System.*
"""
        
        return document.strip()
    
    def update_handover_md_file(self, document_content: str) -> str:
        """Update the LLM_HANDOVER.md file with new content"""
        
        handover_file = "LLM_HANDOVER.md"
        
        try:
            # Backup existing file
            if os.path.exists(handover_file):
                backup_file = f"{handover_file}.backup.{int(datetime.now().timestamp())}"
                with open(handover_file, 'r') as src, open(backup_file, 'w') as dst:
                    dst.write(src.read())
            
            # Write new content
            with open(handover_file, 'w') as f:
                f.write(document_content)
            
            return handover_file
            
        except Exception as e:
            raise Exception(f"Failed to update handover document: {e}")
    
    def _get_detailed_git_info(self) -> str:
        """Get detailed git repository information"""
        
        try:
            repo = git.Repo(search_parent_directories=True)
            
            # Get recent commits
            commits = []
            for commit in repo.iter_commits(max_count=5):
                commits.append(f"*   `{commit.hexsha[:8]} - {commit.summary}`")
            
            # Get current status
            status_info = []
            if repo.is_dirty():
                status_info.append("**Repository Status:** Modified (uncommitted changes)")
                
                # Get detailed status
                if repo.untracked_files:
                    status_info.append(f"**Untracked Files:** {len(repo.untracked_files)} files")
                
                modified_files = [item.a_path for item in repo.index.diff(None)]
                if modified_files:
                    status_info.append(f"**Modified Files:** {len(modified_files)} files")
                    
                staged_files = [item.a_path for item in repo.index.diff("HEAD")]
                if staged_files:
                    status_info.append(f"**Staged Files:** {len(staged_files)} files")
            else:
                status_info.append("**Repository Status:** Clean (no uncommitted changes)")
            
            git_section = f"""
**Last 5 Commits (most recent first):**
{chr(10).join(commits)}

{chr(10).join(status_info)}
"""
            
            return git_section.strip()
            
        except Exception as e:
            return f"**Git Information:** Unable to retrieve git information: {e}"
    
    def _generate_work_summary(self, state: HandoverState) -> str:
        """Generate summary of work completed in session"""
        
        summary_items = []
        
        # Analyze files touched
        if state.active_files:
            summary_items.append(f"**Files Modified:** Working with {len(state.active_files)} active files")
            
            # Group by file type
            file_types = {}
            for file_path in state.active_files:
                ext = Path(file_path).suffix or "no extension"
                file_types[ext] = file_types.get(ext, 0) + 1
            
            type_summary = ", ".join([f"{count} {ext}" for ext, count in file_types.items()])
            summary_items.append(f"    *   File types: {type_summary}")
        
        # Analyze conversation context
        if state.conversation_context:
            if state.conversation_context.get('total_cost', 0) > 0:
                summary_items.append(f"**Total Cost:** ${state.conversation_context['total_cost']:.4f}")
            
            if state.conversation_context.get('num_exhausted_context_windows', 0) > 0:
                summary_items.append(f"**Context Windows Exhausted:** {state.conversation_context['num_exhausted_context_windows']}")
        
        # Analyze pending operations
        if state.pending_operations:
            summary_items.append(f"**Pending Operations:** {len(state.pending_operations)} operations in queue")
        
        # Default message if no specific work identified
        if not summary_items:
            summary_items.append("**Session Activity:** Interactive coding session in progress")
        
        return "\n".join(summary_items)
    
    def _generate_pending_tasks(self, state: HandoverState) -> str:
        """Generate pending tasks section"""
        
        tasks = []
        
        # From pending operations
        if state.pending_operations:
            tasks.append("**Immediate Tasks:**")
            for i, op in enumerate(state.pending_operations, 1):
                tasks.append(f"{i}. {op.get('description', 'Unknown operation')}")
        
        # From file context
        if state.active_files:
            tasks.append("**File Context Tasks:**")
            tasks.append("*   Continue working with the currently active files")
            tasks.append("*   Review and commit changes when appropriate")
        
        # From git status
        git_info = self.handover_manager._get_git_status()
        if git_info.get('untracked') or git_info.get('modified'):
            tasks.append("**Git Tasks:**")
            if git_info.get('untracked'):
                tasks.append(f"*   Review {len(git_info['untracked'])} untracked files")
            if git_info.get('modified'):
                tasks.append(f"*   Address {len(git_info['modified'])} modified files")
        
        # Default if no specific tasks
        if not tasks:
            tasks.append("*   Continue with development tasks as requested by user")
            tasks.append("*   Review current file context and conversation history")
            tasks.append("*   Maintain existing workflow and user preferences")
        
        return "\n".join(tasks)
    
    def _generate_next_instructions(self, state: HandoverState) -> str:
        """Generate instructions for next LLM"""
        
        instructions = [
            "*   **State Restoration:** Load the handover state from `.aider.handover.state.json` to restore complete session context",
            "*   **Validation:** Verify the state checksum and file accessibility before proceeding",
            "*   **Model Configuration:** Ensure the same model configuration is used for consistency",
            "*   **File Context:** Review the active and read-only files to understand the current working set",
            "*   **Conversation Context:** Review the chat history summary to understand user preferences and recent interactions",
            "*   **User Preferences:** Maintain the established edit format and coder type preferences"
        ]
        
        # Add specific instructions based on state
        if state.pending_operations:
            instructions.append("*   **Pending Operations:** Complete the operations listed in the pending tasks section")
        
        if state.current_coder_type != "unknown":
            instructions.append(f"*   **Coder Type:** Continue using the {state.current_coder_type} coder for consistency")
        
        if state.edit_format != "unknown":
            instructions.append(f"*   **Edit Format:** Maintain the {state.edit_format} edit format")
        
        return "\n".join(instructions)
    
    def _format_file_list(self, files: List[str]) -> str:
        """Format file list for documentation"""
        if not files:
            return "*   (none)"
        
        formatted_files = []
        for file_path in files:
            # Show relative path if possible
            try:
                rel_path = os.path.relpath(file_path)
                if len(rel_path) < len(file_path):
                    formatted_files.append(f"*   `{rel_path}`")
                else:
                    formatted_files.append(f"*   `{file_path}`")
            except ValueError:
                formatted_files.append(f"*   `{file_path}`")
        
        return "\n".join(formatted_files)
    
    def _format_token_usage(self, token_usage: Dict[str, int]) -> str:
        """Format token usage information"""
        if not token_usage:
            return "No token usage data available"
        
        formatted = []
        for key, value in token_usage.items():
            formatted.append(f"{key}: {value:,}")
        
        return ", ".join(formatted) if formatted else "No token usage data"
    
    def _format_success_metrics(self, success_metrics: Dict[str, Any]) -> str:
        """Format success metrics information"""
        if not success_metrics:
            return "No success metrics available"
        
        formatted = []
        for key, value in success_metrics.items():
            formatted.append(f"{key}: {value}")
        
        return ", ".join(formatted) if formatted else "No success metrics"
    
    def _format_env_vars(self, env_vars: Dict[str, str]) -> str:
        """Format environment variables (safe ones only)"""
        if not env_vars:
            return "*   (none)"
        
        # Only show safe environment variables
        safe_vars = {k: v for k, v in env_vars.items() 
                    if not any(sensitive in k.lower() 
                              for sensitive in ['key', 'secret', 'token', 'password'])}
        
        if not safe_vars:
            return "*   (no safe variables to display)"
        
        formatted = []
        for key, value in sorted(safe_vars.items()):
            # Truncate long values
            display_value = value if len(value) <= 50 else f"{value[:47]}..."
            formatted.append(f"*   `{key}`: {display_value}")
        
        return "\n".join(formatted)
    
    def _format_user_preferences(self, preferences: Dict[str, Any]) -> str:
        """Format user preferences"""
        if not preferences:
            return "*   (none captured)"
        
        formatted = []
        for key, value in preferences.items():
            formatted.append(f"*   `{key}`: {value}")
        
        return "\n".join(formatted) if formatted else "*   (none captured)"